In [4]:
import pandas as pd

file = './data/ccs/CCS_Data/121-5546.csv'
df = pd.read_csv(file)

In [10]:
df.head()

,Time,BinDuration,Volume,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,AvgSpeed
0,2018-08-01 00:00:00,300,220,1.0,169.0,16.0,0.0,0.0,2.0,0.0,2.0,26.0,0.0,2.0,2.0,0.0,0.0,0.0,68.4
1,2018-08-01 00:05:00,300,213,1.0,154.0,17.0,0.0,0.0,2.0,0.0,5.0,30.0,0.0,2.0,2.0,0.0,0.0,0.0,69.0
2,2018-08-01 00:10:00,300,255,2.0,174.0,27.0,0.0,0.0,0.0,0.0,9.0,36.0,0.0,2.0,5.0,0.0,0.0,0.0,67.9
3,2018-08-01 00:15:00,300,253,0.0,180.0,28.0,0.0,3.0,0.0,0.0,5.0,33.0,0.0,1.0,3.0,0.0,0.0,0.0,67.6
4,2018-08-01 00:20:00,300,249,0.0,191.0,22.0,0.0,2.0,0.0,0.0,4.0,28.0,0.0,1.0,1.0,0.0,0.0,0.0,68.0

In [12]:
df[100000:].head()

,Time,BinDuration,Volume,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,AvgSpeed
100000,2019-07-26 05:20:00,300,433,2.0,274.0,82.0,1.0,6.0,4.0,0.0,8.0,49.0,1.0,4.0,2.0,0.0,0.0,0.0,72.2
100001,2019-07-26 05:25:00,300,456,0.0,306.0,82.0,3.0,7.0,4.0,0.0,3.0,46.0,0.0,2.0,3.0,0.0,0.0,0.0,72.1
100002,2019-07-26 05:30:00,300,575,0.0,360.0,118.0,0.0,5.0,4.0,0.0,12.0,73.0,0.0,2.0,1.0,0.0,0.0,0.0,71.8
100003,2019-07-26 05:35:00,300,571,0.0,338.0,144.0,1.0,20.0,1.0,0.0,14.0,49.0,1.0,1.0,1.0,1.0,0.0,0.0,71.4
100004,2019-07-26 05:40:00,300,612,3.0,385.0,143.0,1.0,10.0,5.0,0.0,7.0,57.0,0.0,1.0,0.0,0.0,0.0,0.0,72.2

In [17]:
df[100000:].tail(10)

,Time,BinDuration,Volume,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,AvgSpeed
205046,2020-07-31 23:10:00,300,364,0.0,290.0,40.0,0.0,2.0,0.0,0.0,3.0,24.0,0.0,2.0,3.0,0.0,0.0,0.0,71.3
205047,2020-07-31 23:15:00,300,406,1.0,331.0,47.0,1.0,2.0,2.0,0.0,5.0,15.0,0.0,0.0,2.0,0.0,0.0,0.0,71.8
205048,2020-07-31 23:20:00,300,344,0.0,278.0,36.0,2.0,1.0,1.0,0.0,1.0,19.0,0.0,5.0,1.0,0.0,0.0,0.0,71.9
205049,2020-07-31 23:25:00,300,389,0.0,295.0,49.0,2.0,4.0,0.0,0.0,6.0,25.0,0.0,5.0,3.0,0.0,0.0,0.0,71.4
205050,2020-07-31 23:30:00,300,364,1.0,284.0,41.0,0.0,3.0,2.0,0.0,4.0,23.0,0.0,5.0,1.0,0.0,0.0,0.0,71.7
205051,2020-07-31 23:35:00,300,403,0.0,296.0,45.0,1.0,3.0,3.0,0.0,12.0,34.0,0.0,5.0,4.0,0.0,0.0,0.0,71.2
205052,2020-07-31 23:40:00,300,344,2.0,280.0,34.0,0.0,2.0,2.0,0.0,4.0,14.0,0.0,1.0,5.0,0.0,0.0,0.0,71.4
205053,2020-07-31 23:45:00,300,322,0.0,252.0,39.0,3.0,1.0,1.0,0.0,2.0,22.0,0.0,1.0,1.0,0.0,0.0,0.0,72.0
205054,2020-07-31 23:50:00,300,307,0.0,252.0,28.0,1.0,0.0,1.0,0.0,3.0,19.0,0.0,2.0,1.0,0.0,0.0,0.0,72.2
205055,2020-07-31 23:55:00,300,313,0.0,250.0,28.0,1.0,6.0,1.0,0.0,7.0,18.0,0.0,0.0,2.0,0.0,0.0,0.0,70.6